controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.45 
  min_vel_x: 0.1 
  max_vel_theta: 1.0 

  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.14
  acc_lim_x: 2.5 
  acc_lim_y: 2.5 

  sim_time: 3.0

  vx_samples: 5.0
  vtheta_samples: 10.0

  path_distance_bias: 0.6 
  goal_distance_bias: 0.8 
  occdist_scale: 0.02

  holonomic_robot: true #false
  meter_scoring: true