global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 2.0
   publish_frequency: 2.0 
   width: 40.0
   height: 40.0
   origin_x: 0
   origin_y: 0
   resolution: 0.05
   static_map: true
   rolling_window: false